adding k6

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Build and Push Docker Image 🚀
+name: Build, Test, and Push Docker Image 🚀
 
 on:
   push:
@@ -24,3 +24,37 @@ jobs:
 
       - name: Push image to Docker Hub
         run: docker push yuriy235/carrentalblazor
+
+  test:
+    runs-on: ubuntu-latest
+    needs: build
+    
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Set up Docker Compose
+        run: |
+          docker-compose down || true
+          docker-compose up -d
+      
+      - name: Wait for the application to be ready
+        run: |
+          echo "Waiting for the application to start..."
+          for i in {1..30}; do
+            if curl -s http://localhost:7063/api/users > /dev/null; then
+              echo "Application is ready!"
+              exit 0
+            fi
+            sleep 2
+          done
+          echo "Application failed to start."
+          exit 1
+
+      - name: Run K6 performance tests
+        run: |
+          docker run --network="host" -v ${{ github.workspace }}/load-tests:/scripts loadimpact/k6 run /scripts/constant_vus_test.js
+
+      - name: Tear down Docker Compose
+        if: always()
+        run: docker-compose down
